coverartarchive:
  host: http://coverartarchive.org
mongodb:
  password: FTE3WVwtqUDGIOMB
  url: mongodb+srv://plugsurfing-challenge:<password>@playground.gflqb30.mongodb.net/?retryWrites=true&w=majority
  username: plugsurfing-challenge
musicbrainz:
  host: http://musicbrainz.org/ws/2
spring:
  data:
    mongodb:
      database: plugsurfingChallenge
      password: FTE3WVwtqUDGIOMB
      username: plugsurfing-challenge
      uri: mongodb+srv://${spring.data.mongodb.username}:${spring.data.mongodb.password}@playground.gflqb30.mongodb.net/?retryWrites=true&w=majority
wikidata:
  host: https://www.wikidata.org/wiki/Special:EntityData
wikipedia:
  host: https://en.wikipedia.org/api/rest_v1

