coverartarchive:
  apiUrl: http://coverartarchive.org
musicbrainz:
  apiUrl: http://musicbrainz.org/ws/2
spring:
  data:
    mongodb:
      database: plugsurfingChallenge
      password: FTE3WVwtqUDGIOMB
      username: plugsurfing-challenge
      uri: mongodb+srv://${spring.data.mongodb.username}:${spring.data.mongodb.password}@playground.gflqb30.mongodb.net/?retryWrites=true&w=majority
wikidata:
  apiUrl: https://www.wikidata.org/wiki/Special:EntityData
wikipedia:
  apiUrl: https://en.wikipedia.org/api/rest_v1

